name: CD - Run on Release

on:
  release:
    types: [created]

jobs:
  run-on-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run script
      run: |
        echo "ðŸŽŠ This is CD! Running because a release was created."
        python liarsDice.py
        echo "Release version: ${{ github.event.release.tag_name }}"